spring.application.name=JobProcessing

spring.datasource.url=jdbc:postgresql://localhost:60372/mydatabase
#spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=myuser
spring.datasource.password=secret
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true

spring.docker.compose.enabled=true

worker.count=1
job.max-attempts=5
job.max-duration=10
job.processing-time=5000

recovery.intervall=5
